17-rails-review-allergens/allergen-lab-111819/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show, :destroy]
  resources :recipes, only: [:index, :new, :create] 
  get '/recipes/sort', to: "recipes#sort", as: 'recipes_sort'

  resources :ingredients, only: [:index, :show]
end

17-rails-review-allergens/allergen-lab-111819/app/models/allergen.rb
class Allergen < ApplicationRecord
    belongs_to :user
    belongs_to :ingredient
end

17-rails-review-allergens/allergen-lab-111819/app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :recipe_ingredients
    has_many :recipes, through: :recipe_ingredients
    has_many :allergens
end

17-rails-review-allergens/allergen-lab-111819/app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    has_many :recipe_ingredients
    has_many :ingredients, through: :recipe_ingredients

end

17-rails-review-allergens/allergen-lab-111819/app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
    belongs_to :recipe
    belongs_to :ingredient
end

17-rails-review-allergens/allergen-lab-111819/app/models/user.rb
class User < ApplicationRecord
    has_many :recipes
    has_many :allergens
end

17-rails-review-allergens/allergen-lab-111819/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

17-rails-review-allergens/allergen-lab-111819/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

    def index
        @ingredients = Ingredient.all.sort_by{|ing| ing.allergens.length}.reverse
    end

    def show
        @ingredient = Ingredient.find(params[:id])
    end
end

17-rails-review-allergens/allergen-lab-111819/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    def index
        @recipes = Recipe.all
    end

    def sort
        @recipes = Recipe.all.sort_by{|recipe| recipe.ingredients.length}
        render :index
    end

    def new
        @recipe = Recipe.new
    end

    def create
        @recipe = Recipe.new(name: params["recipe"]["name"], user_id:params["recipe"]["user_id"])
        if @recipe.save
            redirect_to recipes_path
        else
            flash("There was an error!")
            redirect_to new_recipe_path
        end

    end

end

17-rails-review-allergens/allergen-lab-111819/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_path
    end
end

17-rails-review-allergens/allergen-lab-111819/app/helpers/application_helper.rb
module ApplicationHelper
end

17-rails-review-allergens/allergen-lab-111819/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

17-rails-review-allergens/allergen-lab-111819/app/helpers/recipes_helper.rb
module RecipesHelper
end

17-rails-review-allergens/allergen-lab-111819/app/helpers/users_helper.rb
module UsersHelper
end

17-rails-review-allergens/allergen-lab-111819/app/views/ingredients/index.html.erb
<h1>Ingredients</h1>

<ul>
    <% @ingredients.each do |ing| %>
        <li><%= link_to "#{ing.name}", ingredient_path(ing) %></li>
    <% end %>
</ul>

17-rails-review-allergens/allergen-lab-111819/app/views/ingredients/show.html.erb
<h1><%= @ingredient.name %></h1>

<h2>Recipes</h2>
<ul>
    <% @ingredient.recipes.each do |recipe| %>
        <ul><%= recipe.name %></ul>
    <% end %>
</ul>

17-rails-review-allergens/allergen-lab-111819/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AllergenLab111819</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

17-rails-review-allergens/allergen-lab-111819/app/views/recipes/index.html.erb
<h1>Recipes</h1>


    <%= link_to "Sort", recipes_sort_path %>

<ul>
    <% @recipes.each do |recipe| %>
        <li><%= recipe.name %></li>
    <% end %>
</ul>

17-rails-review-allergens/allergen-lab-111819/app/views/recipes/new.html.erb
<h1>Add a Recipe</h1>

<%= form_for @recipe do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br/>
    <%= f.collection_select :user_id, User.all, :id, :name %>
    <br/>
    <%= f.submit %>
<% end %>

17-rails-review-allergens/allergen-lab-111819/app/views/users/index.html.erb
<h1>Users</h1>

<ul>
    <% @users.each do |user| %>
        <li><%= user.name %></li>
    <% end %>
</ul>

17-rails-review-allergens/allergen-lab-111819/app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<ul>
    <% @user.recipes.each do |recipe| %>
        <li><%= recipe.name %></li>
    <% end %>
</ul>

    <%= button_to 'Delete User', user_path(@user), method: "delete" %>