16-rails-forms-associations/doctoroffice/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :doctors
  resources :patients


end

16-rails-forms-associations/doctoroffice/app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :patients
end

16-rails-forms-associations/doctoroffice/app/models/patient.rb
class Patient < ApplicationRecord
    belongs_to :doctor
end

16-rails-forms-associations/doctoroffice/app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

    require 'faker'

    def index
        @doctors = Doctor.all

        @images  = ["1-doctor.jpg", "2-doctor.jpg", "3-doctor.jpg", "4-doctor.jpg", "5-doctor.jpg"]
        @random_no = rand(1...5)
        @random_image = @images[@random_no]
    end

    def show
        @doctor = Doctor.find(params[:id])
    end

    def new
        @doctor = Doctor.new   
    end

    def create
        @doctor = Doctor.create(doctor_params)
        redirect_to doctors_path(@doctor)
    end

    def edit
        @doctor = Doctor.find(params[:id])
    end

    def update
        @doctor = Doctor.find(params[:id])
        @doctor.update(doctor_params)

        redirect_to @doctor
    end

    def destroy
        @doctor = Doctor.find(params[:id])
        @doctor.destroy

        redirect_to doctors_path
    end

    private

    def doctor_params
        params.require(:doctor).permit(:name, :specialty)
    end
end

16-rails-forms-associations/doctoroffice/app/controllers/patients_controller.rb
class PatientsController < ApplicationController

    def index
        @patients = Patient.all

        @images  = ["1-doctor.jpg", "2-doctor.jpg", "3-doctor.jpg", "4-doctor.jpg", "5-doctor.jpg"]
        @random_no = rand(1...5)
        @random_image = @images[@random_no]
    end

    def show
        @patient = Patient.find(params[:id])
    end

    def new
        @patient = Patient.new
    end

    def create
        @patient = Patient.create(patients_params)
        redirect_to patients_path
    end

    def edit
        @patient = Patient.find(params[:id])
    end

    def update
        @patient = Patient.find(params[:id])
        @patient.update(patients_params)

        redirect_to @patient
    end

    def destroy
        @patient = Patient.find(params[:id])
        @patient.destroy
        
        redirect_to patients_path
    end

    private

    def patients_params
        params.require(:patient).permit(:name, :condition, :doctor_id)
    end
end

16-rails-forms-associations/doctoroffice/app/helpers/doctors_helper.rb
module DoctorsHelper
end

16-rails-forms-associations/doctoroffice/app/views/doctors/edit.html.erb
<div class="container" style="padding-top: 30px;">
        <h1 class="display-3" style="padding-top: 30px;">Edit Doctors Form</h1>
        <br/>
        <p>Made a boo-boo? Change your file using this form. </p>
    </div>
    
    <div class="container" style="padding-top: 30px;">
        <%= form_for @doctor do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
    
        <%= f.label :specialty %>
        <%= f.text_field :specialty %>
    
        <%= f.submit %>
        <% end %>

        <%= button_to "Delete", doctor_path(@doctor), method: :delete %>

    </div>

16-rails-forms-associations/doctoroffice/app/views/doctors/index.html.erb
<h1 class="display-3" style="padding-top: 30px;">Our Family of Doctors</h1>

<div class="container">
    <div class="row row-cols-2">

        <div class="col">
            <h2 style="padding: 15px;">Featured Doctor: Doctor Who</h2>
            <div style="padding: 20px;"><%= image_tag (@random_image) %></div>
            <p>A time-traveling immortal hailing from Gallifrey, Doctor Who specializes in otherworldly illnesses and saving the day. He's currently accepting patients and looks forward to becoming your new best friend. </p>
        </div>

        <div class="col"> 
            <ul style= "list-style-type: none;">
                <% @doctors.each do |doctor| %>
                <li style="padding-top: 20px;"><h6><%= link_to doctor.name, doctor %>, <%= doctor.specialty %></h6></li>
                <% end %>
            </ul>
        </div>

    </div>
</div>

<div class="container" style="padding-top: 30px;">
    <h3>Newly regenerated? Add yourself to the family <%= link_to "here.", "/doctors/new" %></h3>
</div>

16-rails-forms-associations/doctoroffice/app/views/doctors/new.html.erb
<div class="container" style="padding-top: 30px;">
    <h1 class="display-3" style="padding-top: 30px;">New Doctors Form</h1>
    <br/>
    <p>Are you new to our family of practitioners? Add yourself to our database using this form. </p>
</div>

<div class="container" style="padding-top: 30px;">
    <%= form_for @doctor do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>


    <%= f.label :specialty %>
    <%= f.text_field :specialty %>

    <%= f.submit %>
    <% end %>
</div>

16-rails-forms-associations/doctoroffice/app/views/doctors/show.html.erb
<div class="container">
    <h1 class="display-3" style="padding-top: 30px;"><%= @doctor.name %></h1>
    <br/>
</div>

<div class="container">
    <h1 class="display-6"><%= @doctor.specialty %></h1>
    <br>
    <p>Dolores quis quia ad quo voluptates. Maxime delectus totam numquam. Necessitatibus vel atque qui dolore. Id neque nemo. Dolores iusto facere est ad. Accusamus ipsa dolor ut. Et officiis ut hic. Sunt asperiores minus distinctio debitis ipsa dolor. Minima eos deleniti.</p>
</div>

<div class="container" style="padding-top: 50px;">
    <p>Not your flavor? Learn about another doctor, <%= link_to "here.", "/doctors" %></p>
    <p>To edit your file, click <%= link_to "here.", edit_doctor_path(@doctor) %></p>
</div>

16-rails-forms-associations/doctoroffice/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tardis' Medical Bay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
          <a class="navbar-brand" href="/doctors">Tardis Medical Center</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">

              <li class="nav-item active">
                <a class="nav-link" href="/doctors">Doctors</a>
              </li>

              <li class="nav-item">
                  <a class="nav-link" href="/patients">Patients</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="/patients/new">New Patients</a>
              </li>

              <li class="nav-item">
                  <a class="nav-link" href="/doctors/new">For Our New Doctors</a>
              </li>
            </ul>
          </div>
        </nav>

    <%= yield %>
  </body>
</html>

16-rails-forms-associations/doctoroffice/app/views/patients/edit.html.erb
<div class="container" style="padding-top: 30px;">
    <h1 class="display-3" style="padding-top: 30px;">Edit Patients Form</h1>
    <br/>
    <p>Made a boo-boo? Change your file using this form. </p>
</div>
    
<div class="container" style="padding-top: 30px;">
    <%= form_for @patient do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    
    <%= f.label :condition %>
    <%= f.text_field :condition %>
    
    <%= f.submit %>
    <% end %>

    <%= button_to "Delete", patient_path(@patient), method: :delete %>
</div>

16-rails-forms-associations/doctoroffice/app/views/patients/index.html.erb
<h1 class="display-3" style="padding-top: 30px;">Patients List</h1>

<div class="container">
    <div class="row row-cols-2">

        <div class="col">
            <h2 style="padding: 15px;">Featured Patient: Javi</h2>
            <div style="padding: 20px;"><%= image_tag (@random_image) %></div>
            <p>Javi is our star patient- he is here every week 'cause he's always cold. BRRR... </p>
        </div>

        <div class="col"> 
            <ul style= "list-style-type: none;">
                <% @patients.each do |patient| %>
                <li style="padding-top: 20px;"><h6><%= link_to patient.name, patient %>, <%= patient.condition %></h6></li>
                <% end %>
            </ul>
        </div>

    </div>
</div>

<div class="container" style="padding-top: 30px;">
    <h3>Need to be a new patient? Go <%= link_to "here.", new_patient_path %></h3>
</div>

16-rails-forms-associations/doctoroffice/app/views/patients/new.html.erb
<div class="container" style="padding-top: 30px;">
        <h1 class="display-3" style="padding-top: 30px;">New Patients Form</h1>
        <br/>
        <p>Add yourself to our database using this form. </p>
    </div>
    
    <div class="container" style="padding-top: 30px;">
        <%= form_for @patient do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
    
    
        <%= f.label :condition %>
        <%= f.text_field :condition %>

        <%= f.label "Choose your doctor..." %>
        <%= collection_select(:patient, :doctor_id, Doctor.all, :id, :name) %>
    
        <%= f.submit %>
        <% end %>
    </div>

16-rails-forms-associations/doctoroffice/app/views/patients/show.html.erb
<div class="container">
        <h1 class="display-3" style="padding-top: 30px;"><%= @patient.name %></h1>
        <br/>
    </div>
    
    <div class="container">
        <h1 class="display-6"><%= @patient.condition %></h1>
        <br>
        <p>Dolores quis quia ad quo voluptates. Maxime delectus totam numquam. Necessitatibus vel atque qui dolore. Id neque nemo. Dolores iusto facere est ad. Accusamus ipsa dolor ut. Et officiis ut hic. Sunt asperiores minus distinctio debitis ipsa dolor. Minima eos deleniti.</p>
    </div>

    <div class="container">
        <h1 class="display-6">
            Doctor Associated: 
            <%= @patient.doctor_id %>
        </h1>
    </div>
    
    <div class="container" style="padding-top: 50px;">
        <p>Not your patient? Learn about another person to steal monies from, <%= link_to "here.", "/patients" %></p>
        <p>To edit your file, click <%= link_to "here.", edit_patient_path(@patient) %></p>
    </div>